default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: <%= ENV['DEVELOPMENT_DATABASE'] %>

test: &test
  <<: *default
  database: <%= ENV['TEST_DATABASE'] %>

cucumber:
  <<: *test

production:
  <<: *default
  database: <%= ENV['PRODUCTION_DATABASE_NAME'] %>
  username: <%= ENV['PRODUCTION_DATABASE_USER'] %>
  password: <%= ENV['PRODUCTION_DATABASE_PASSWORD'] %>
  host: localhost
  port: 5432
